### ISSUE TITLE
Kurtosis sdk engine gets stopped - unhandled panic

### ISSUE THREAD

**Issue by bhakiyakalimuthu** [kurtosis-tech/kurtosis-sdk#4]
## 📝 Issue Summary
I recently upgraded the Kurtosis CLI version from 0.64.2  to 0.65.0 and I am now unable to use the Kurtosis engine, as it stops running when any of the enclave commands are passed via the CLI.

## ⛱ Steps to reproduce 

- Upgrade kurtosis cli to  v0.65.0 
- Check the status of engine (status running)
- Try to create enclave or list enclave
- Immediately cli throws error and unable to use kurtosis further
- Engine is not running and completely crashed.
- Unhandled panic inside the engine

## ⛱ OS Info

- OS : Mac OSX ventura 13.1 M1

## 📚 Steps followed to fix this issue

1. Uninstall kurtosis cli
2. brew clean up
3. Restart the machine
4. Install kurtosis cli
But above steps didn't help

I performed `kurtosis clean -a`. Then it started working though.

## 📚 References
![image](https://user-images.githubusercontent.com/7114614/216073801-3d2884ff-ace0-4c81-8cb0-f8cc2e103bec.png)

Kurtosis docker engine logs for reference
```golang
> ❯ docker logs 42cb3020c157
INFO[2023-02-01T14:12:34Z][main.go:runMain] Running server...
DEBU[2023-02-01T14:12:35Z][server.go:func1] Received gRPC request to method '/engine_api.EngineService/GetEngineInfo' with args:
DEBU[2023-02-01T14:12:35Z][server.go:func1] gRPC request to method '/engine_api.EngineService/GetEngineInfo' succeeded with response:
engine_version:"0.65.0"
DEBU[2023-02-01T14:13:29Z][server.go:func1] Received gRPC request to method '/engine_api.EngineService/GetEngineInfo' with args:
DEBU[2023-02-01T14:13:29Z][server.go:func1] gRPC request to method '/engine_api.EngineService/GetEngineInfo' succeeded with response:
engine_version:"0.65.0"
DEBU[2023-02-01T14:13:29Z][server.go:func1] Received gRPC request to method '/engine_api.EngineService/GetEngineInfo' with args:
DEBU[2023-02-01T14:13:29Z][server.go:func1] gRPC request to method '/engine_api.EngineService/GetEngineInfo' succeeded with response:
engine_version:"0.65.0"
DEBU[2023-02-01T14:13:29Z][server.go:func1] Received gRPC request to method '/engine_api.EngineService/GetEngineInfo' with args:
DEBU[2023-02-01T14:13:29Z][server.go:func1] gRPC request to method '/engine_api.EngineService/GetEngineInfo' succeeded with response:
engine_version:"0.65.0"
DEBU[2023-02-01T14:13:29Z][server.go:func1] Received gRPC request to method '/engine_api.EngineService/GetEnclaves' with args:
panic: runtime error: slice bounds out of range [:12] with length 9

goroutine 13 [running]:
github.com/kurtosis-tech/kurtosis/container-engine-lib/lib/uuid_generator.ShortenedUUIDString(...)
	/home/circleci/project/container-engine-lib/lib/uuid_generator/uuid_generator.go:41
github.com/kurtosis-tech/kurtosis/engine/server/engine/enclave_manager.(*EnclaveManager).getEnclaveInfoForEnclave(0xc0000bd7b0?, {0x1b06260?, 0xc0000ae5d0?}, 0xc00022aa80)
	/home/circleci/project/engine/server/engine/enclave_manager/enclave_manager.go:608 +0x2ec
github.com/kurtosis-tech/kurtosis/engine/server/engine/enclave_manager.(*EnclaveManager).getEnclavesWithoutMutex(0xc0000b0a00, {0x1b06260, 0xc0000ae5d0})
	/home/circleci/project/engine/server/engine/enclave_manager/enclave_manager.go:503 +0x1a5
github.com/kurtosis-tech/kurtosis/engine/server/engine/enclave_manager.(*EnclaveManager).GetEnclaves(0x46e05e?, {0x1b06260?, 0xc0000ae5d0?})
	/home/circleci/project/engine/server/engine/enclave_manager/enclave_manager.go:243 +0xe5
github.com/kurtosis-tech/kurtosis/engine/server/engine/server.(*EngineServerService).GetEnclaves(0xc0001afd50?, {0x1b06260?, 0xc0000ae5d0?}, 0x10?)
	/home/circleci/project/engine/server/engine/server/engine_server_service.go:92 +0x2b
github.com/kurtosis-tech/kurtosis/api/golang/engine/kurtosis_engine_rpc_api_bindings._EngineService_GetEnclaves_Handler.func1({0x1b06260, 0xc0000ae5d0}, {0x1712440?, 0xc0000ae600})
	/home/circleci/project/api/golang/engine/kurtosis_engine_rpc_api_bindings/engine_service_grpc.pb.go:264 +0x78
github.com/kurtosis-tech/minimal-grpc-server/golang/server.MinimalGRPCServer.RunUntilStopped.func1({0x1b06260, 0xc0000ae5d0}, {0x1712440, 0xc0000ae600}, 0xc0000e1ae0?, 0xc0003dcac8)
	/home/circleci/go/pkg/mod/github.com/kurtosis-tech/minimal-grpc-server/golang@v0.0.0-20211201000847-a204edc5a0b3/server/server.go:55 +0x115
github.com/kurtosis-tech/kurtosis/api/golang/engine/kurtosis_engine_rpc_api_bindings._EngineService_GetEnclaves_Handler({0x1793800?, 0xc0000b0a50}, {0x1b06260, 0xc0000ae5d0}, 0xc00009acc0, 0x1988590)
	/home/circleci/project/api/golang/engine/kurtosis_engine_rpc_api_bindings/engine_service_grpc.pb.go:266 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022c1c0, {0x1b09450, 0xc000488900}, 0xc000146c60, 0xc0002e1e30, 0x2666dd0, 0x0)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00022c1c0, {0x1b09450, 0xc000488900}, 0xc000146c60, 0x0)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:1608 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:923 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:921 +0x28a
```
---

**Comment by h4ck3rk3y** [comment]
This has been fixed in v0.65.1
